// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqLIQ8JrEgKLN2vvjrxf_UXbzPUPmCl9E',
    appId: '1:1083589876021:web:93fbe9c7a0fc491a19547c',
    messagingSenderId: '1083589876021',
    projectId: 'netprimex-57008',
    authDomain: 'netprimex-57008.firebaseapp.com',
    storageBucket: 'netprimex-57008.firebasestorage.app',
    measurementId: 'G-RG2WZVJWMG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTLKJr53CsKg9vRu92l_QoBZfVMVRfVvc',
    appId: '1:1083589876021:ios:4e46993818812e2019547c',
    messagingSenderId: '1083589876021',
    projectId: 'netprimex-57008',
    storageBucket: 'netprimex-57008.firebasestorage.app',
    iosBundleId: 'com.example.movieSplash',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTLKJr53CsKg9vRu92l_QoBZfVMVRfVvc',
    appId: '1:1083589876021:ios:4e46993818812e2019547c',
    messagingSenderId: '1083589876021',
    projectId: 'netprimex-57008',
    storageBucket: 'netprimex-57008.firebasestorage.app',
    iosBundleId: 'com.example.movieSplash',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzASqgXKKurBwV9ZrgLEkxK35pWep2uy0',
    appId: '1:1083589876021:android:eea41044a02fbb6319547c',
    messagingSenderId: '1083589876021',
    projectId: 'netprimex-57008',
    storageBucket: 'netprimex-57008.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqLIQ8JrEgKLN2vvjrxf_UXbzPUPmCl9E',
    appId: '1:1083589876021:web:5990f56175c4b5b119547c',
    messagingSenderId: '1083589876021',
    projectId: 'netprimex-57008',
    authDomain: 'netprimex-57008.firebaseapp.com',
    storageBucket: 'netprimex-57008.firebasestorage.app',
    measurementId: 'G-DZ5H0ELVXM',
  );

}